name: Delete old workflow runs
on:
  schedule:
    - cron: '50 14 * * 1' # 매주 월요일 23:50 KST (UTC 기준 14:50)
  workflow_dispatch: # 수동 실행 가능

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: JuvenileQ/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 2
